init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "6.11.5"

cache:
 - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # # Update npm
  # # There seems to be issues with npm 5.4 in Windows
  # # See https://github.com/npm/npm/issues/18380
  # - npm install -g npm@6.1.0

os: Visual Studio 2015
# before_build:
#   - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build_script:
  - cmd: build.cmd
test: off
# version: 0.0.1.{build}
artifacts:
# https://ci.appveyor.com/api/projects/fable-compiler/Fable/artifacts/src/dotnet/Fable.JS/repl.zip
  - path: src\dotnet\Fable.JS\out
    name: repl
    type: zip
# https://ci.appveyor.com/api/projects/fable-compiler/Fable/artifacts/src/dotnet/Fable.JS/repl-bundle.zip
  - path: src\dotnet\Fable.JS\bundle
    name: repl-bundle
    type: zip
