init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

# Test against this version of Node.js
environment:
  nodejs_version: "5.4"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

os: Visual Studio 2015
before_build:
  - cmd: before_build.cmd
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: build
    name: build

test_script:
  - node tools/fable2babel.js --projFile test/Fable.Tests.fsproj
  - npm run test
  - cd test
  - node ../tools/fable2babel.js --projFile HelloWorld.fsx
  - cd ..
  - if not exist "C:\temp" mkdir C:\temp
  - copy test C:\temp
  - node tools\fable2babel.js --projFile "C:\Temp\HelloWorld.fsproj"
  - cd sample\node\server
  - npm install
  - cd ..\..\..
  - node tools/fable2babel.js --projFile sample/node/server/app.fsx
  - cd sample\browser\todomvc
  - npm install
  - cd ..\..\..
  - node tools/fable2babel.js --projFile sample/browser/todomvc/app.fsx
  - node sample/node/server/app.js 8090

 