name: package_simple
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^2.0.1
